name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  ci:
    name: Build and test wheel distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/photoshop-connection
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: Build package
        run: uv build --wheel

      - name: Test
        run: uv run pytest

      - name: Publish package
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1